#include "config.hpp"

DISABLE_WARNING_PUSH

DISABLE_WARNING_PEDANTIC
DISABLE_WARNING_CONVERSION
DISABLE_WARNING_ENUM_COMPARE
DISABLE_WARNING_USELESS_CAST
DISABLE_WARNING_DUPLICATE_BRANCHES
DISABLE_WARNING_NARROWING

#include <extras/raygui.h>

#define GUI_PROPERTY_LIST_IMPLEMENTATION
#include "dm_property_list.h"

DISABLE_WARNING_POP
